export interface BIRRDO {
  code: string;
  name: string;
  location: string;
}

export const birRDOList: BIRRDO[] = [
  { code: '001', name: 'RDO No. 001', location: 'Laoag City, Ilocos Norte' },
  { code: '002', name: 'RDO No. 002', location: 'Vigan City, Ilocos Sur' },
  { code: '003', name: 'RDO No. 003', location: 'San Fernando City, La Union' },
  { code: '004', name: 'RDO No. 004', location: 'Dagupan City, Pangasinan' },
  { code: '005', name: 'RDO No. 005', location: 'Alaminos City, Pangasinan' },
  { code: '006', name: 'RDO No. 006', location: 'Urdaneta City, Pangasinan' },
  { code: '007', name: 'RDO No. 007', location: 'Bangued, Abra' },
  { code: '008', name: 'RDO No. 008', location: 'Baguio City, Benguet' },
  { code: '009', name: 'RDO No. 009', location: 'La Trinidad, Benguet' },
  { code: '010', name: 'RDO No. 010', location: 'Bontoc, Mountain Province' },
  { code: '011', name: 'RDO No. 011', location: 'Tabuk City, Kalinga' },
  { code: '012', name: 'RDO No. 012', location: 'Lagawe, Ifugao' },
  { code: '013', name: 'RDO No. 013', location: 'Tuguegarao City, Cagayan' },
  { code: '014', name: 'RDO No. 014', location: 'Aparri, Cagayan' },
  { code: '015', name: 'RDO No. 015', location: 'Ilagan City, Isabela' },
  { code: '016', name: 'RDO No. 016', location: 'Cauayan City, Isabela' },
  { code: '017A', name: 'RDO No. 017A', location: 'Bayombong, Nueva Vizcaya' },
  { code: '017B', name: 'RDO No. 017B', location: 'Cabarroguis, Quirino' },
  { code: '018', name: 'RDO No. 018', location: 'Basco, Batanes' },
  { code: '019', name: 'RDO No. 019', location: 'Subic Bay Freeport Zone' },
  { code: '020', name: 'RDO No. 020', location: 'Balanga City, Bataan' },
  { code: '021A', name: 'RDO No. 021A', location: 'North Pampanga (Mabalacat)' },
  { code: '021B', name: 'RDO No. 021B', location: 'South Pampanga (San Fernando)' },
  { code: '022', name: 'RDO No. 022', location: 'Baler, Aurora' },
  { code: '023A', name: 'RDO No. 023A', location: 'North Nueva Ecija (Talavera)' },
  { code: '023B', name: 'RDO No. 023B', location: 'South Nueva Ecija (Cabanatuan)' },
  { code: '024', name: 'RDO No. 024', location: 'Valenzuela City' },
  { code: '025A', name: 'RDO No. 025A', location: 'West Bulacan (Plaridel)' },
  { code: '025B', name: 'RDO No. 025B', location: 'East Bulacan (Sta. Maria)' },
  { code: '026', name: 'RDO No. 026', location: 'Malabon / Navotas City' },
  { code: '027', name: 'RDO No. 027', location: 'Caloocan City' },
  { code: '028', name: 'RDO No. 028', location: 'Novaliches, Quezon City' },
  { code: '029', name: 'RDO No. 029', location: 'Tarlac City, Tarlac' },
  { code: '030', name: 'RDO No. 030', location: 'Binondo, Manila' },
  { code: '031', name: 'RDO No. 031', location: 'Sta. Cruz, Manila' },
  { code: '032', name: 'RDO No. 032', location: 'Quiapo / Sampaloc / Sta. Mesa, Manila' },
  { code: '033', name: 'RDO No. 033', location: 'Intramuros / Ermita / Malate, Manila' },
  { code: '034', name: 'RDO No. 034', location: 'Paco / Pandacan / Sta. Ana, Manila' },
  { code: '038', name: 'RDO No. 038', location: 'North Quezon City' },
  { code: '039', name: 'RDO No. 039', location: 'South Quezon City' },
  { code: '040', name: 'RDO No. 040', location: 'Cubao, Quezon City' },
  { code: '041', name: 'RDO No. 041', location: 'Mandaluyong City' },
  { code: '042', name: 'RDO No. 042', location: 'San Juan City' },
  { code: '043A', name: 'RDO No. 043A', location: 'East Pasig City' },
  { code: '043B', name: 'RDO No. 043B', location: 'West Pasig City' },
  { code: '044', name: 'RDO No. 044', location: 'Taguig City / Pateros' },
  { code: '045', name: 'RDO No. 045', location: 'Marikina City' },
  { code: '046', name: 'RDO No. 046', location: 'Cainta / Taytay, Rizal' },
  { code: '047', name: 'RDO No. 047', location: 'East Rizal (Antipolo City)' },
  { code: '048', name: 'RDO No. 048', location: 'West Rizal' },
  { code: '049', name: 'RDO No. 049', location: 'North Cavite (Kawit)' },
  { code: '050', name: 'RDO No. 050', location: 'South Cavite (Trece Martires)' },
  { code: '051', name: 'RDO No. 051', location: 'Pasay City' },
  { code: '052', name: 'RDO No. 052', location: 'Parañaque City' },
  { code: '053A', name: 'RDO No. 053A', location: 'Las Piñas City' },
  { code: '053B', name: 'RDO No. 053B', location: 'Muntinlupa City' },
  { code: '054A', name: 'RDO No. 054A', location: 'South Makati City' },
  { code: '054B', name: 'RDO No. 054B', location: 'North Makati City' },
  { code: '055', name: 'RDO No. 055', location: 'Cotabato City' },
  { code: '056', name: 'RDO No. 056', location: 'Central Batangas (Tanauan)' },
  { code: '057', name: 'RDO No. 057', location: 'West Batangas (Lian)' },
  { code: '058', name: 'RDO No. 058', location: 'Batangas City' },
  { code: '059', name: 'RDO No. 059', location: 'Lipa City, Batangas' },
  { code: '060', name: 'RDO No. 060', location: 'Lucena City, Quezon' },
  { code: '061', name: 'RDO No. 061', location: 'Calauag, Quezon' },
  { code: '062', name: 'RDO No. 062', location: 'Boac, Marinduque' },
  { code: '063', name: 'RDO No. 063', location: 'Calapan City, Oriental Mindoro' },
  { code: '064', name: 'RDO No. 064', location: 'Mamburao, Occidental Mindoro' },
  { code: '065', name: 'RDO No. 065', location: 'Naga City, Camarines Sur' },
  { code: '066', name: 'RDO No. 066', location: 'Iriga City, Camarines Sur' },
  { code: '067', name: 'RDO No. 067', location: 'Legazpi City, Albay' },
  { code: '068', name: 'RDO No. 068', location: 'Sorsogon City, Sorsogon' },
  { code: '069', name: 'RDO No. 069', location: 'Virac, Catanduanes' },
  { code: '070', name: 'RDO No. 070', location: 'Masbate City, Masbate' },
  { code: '071', name: 'RDO No. 071', location: 'Kalibo, Aklan' },
  { code: '072', name: 'RDO No. 072', location: 'Roxas City, Capiz' },
  { code: '073', name: 'RDO No. 073', location: 'San Jose, Antique' },
  { code: '074', name: 'RDO No. 074', location: 'Iloilo City, Iloilo' },
  { code: '075', name: 'RDO No. 075', location: 'Zarraga, Iloilo' },
  { code: '076', name: 'RDO No. 076', location: 'Victorias City, Negros Occidental' },
  { code: '077', name: 'RDO No. 077', location: 'Bacolod City, Negros Occidental' },
  { code: '078', name: 'RDO No. 078', location: 'Binalbagan, Negros Occidental' },
  { code: '079', name: 'RDO No. 079', location: 'Dumaguete City, Negros Oriental' },
  { code: '080', name: 'RDO No. 080', location: 'Mandaue City, Cebu' },
  { code: '081', name: 'RDO No. 081', location: 'Cebu City North' },
  { code: '082', name: 'RDO No. 082', location: 'Cebu City South' },
  { code: '083', name: 'RDO No. 083', location: 'Talisay City, Cebu' },
  { code: '084', name: 'RDO No. 084', location: 'Tagbilaran City, Bohol' },
  { code: '085', name: 'RDO No. 085', location: 'Catarman, Northern Samar' },
  { code: '086', name: 'RDO No. 086', location: 'Borongan, Eastern Samar' },
  { code: '087', name: 'RDO No. 087', location: 'Calbayog City, Samar' },
  { code: '088', name: 'RDO No. 088', location: 'Tacloban City, Leyte' },
  { code: '089', name: 'RDO No. 089', location: 'Ormoc City, Leyte' },
  { code: '090', name: 'RDO No. 090', location: 'Maasin City, Southern Leyte' },
  { code: '091', name: 'RDO No. 091', location: 'Dipolog City, Zamboanga del Norte' },
  { code: '092', name: 'RDO No. 092', location: 'Pagadian City, Zamboanga del Sur' },
  { code: '093A', name: 'RDO No. 093A', location: 'Zamboanga City' },
  { code: '093B', name: 'RDO No. 093B', location: 'Ipil, Zamboanga Sibugay' },
  { code: '094', name: 'RDO No. 094', location: 'Isabela, Basilan' },
  { code: '095', name: 'RDO No. 095', location: 'Jolo, Sulu' },
  { code: '096', name: 'RDO No. 096', location: 'Bongao, Tawi-Tawi' },
  { code: '097', name: 'RDO No. 097', location: 'Gingoog City, Misamis Oriental' },
  { code: '098', name: 'RDO No. 098', location: 'Cagayan de Oro City' },
  { code: '099', name: 'RDO No. 099', location: 'Malaybalay City, Bukidnon' },
  { code: '100', name: 'RDO No. 100', location: 'Ozamiz City, Misamis Occidental' },
  { code: '101', name: 'RDO No. 101', location: 'Iligan City, Lanao del Norte' },
  { code: '102', name: 'RDO No. 102', location: 'Marawi City, Lanao del Sur' },
  { code: '103', name: 'RDO No. 103', location: 'Butuan City, Agusan del Norte' },
  { code: '104', name: 'RDO No. 104', location: 'Surigao City, Surigao del Norte' },
  { code: '105', name: 'RDO No. 105', location: 'San Francisco, Agusan del Sur' },
  { code: '106', name: 'RDO No. 106', location: 'Tandag City, Surigao del Sur' },
  { code: '107', name: 'RDO No. 107', location: 'Cotabato City, Maguindanao' },
  { code: '108', name: 'RDO No. 108', location: 'Kidapawan City, North Cotabato' },
  { code: '109', name: 'RDO No. 109', location: 'Koronadal City, South Cotabato' },
  { code: '110', name: 'RDO No. 110', location: 'General Santos City' },
  { code: '111', name: 'RDO No. 111', location: 'Tacurong City, Sultan Kudarat' },
  { code: '112', name: 'RDO No. 112', location: 'Tagum City, Davao del Norte' },
  { code: '113A', name: 'RDO No. 113A', location: 'West Davao City' },
  { code: '113B', name: 'RDO No. 113B', location: 'East Davao City' },
  { code: '114', name: 'RDO No. 114', location: 'Mati City, Davao Oriental' },
  { code: '115', name: 'RDO No. 115', location: 'Digos City, Davao del Sur' },
  { code: '116', name: 'RDO No. 116', location: 'Large Taxpayers Audit Division I (LTAD I)' },
  { code: '117', name: 'RDO No. 117', location: 'Large Taxpayers Audit Division II (LTAD II)' },
  { code: '118', name: 'RDO No. 118', location: 'Large Taxpayers Division - Makati' },
  { code: '119', name: 'RDO No. 119', location: 'Large Taxpayers Division - Cebu' },
  { code: '120', name: 'RDO No. 120', location: 'Large Taxpayers Division - Davao' },
  { code: '121', name: 'RDO No. 121', location: 'Excise Large Taxpayers Regulatory Division' },
  { code: '122', name: 'RDO No. 122', location: 'Excise Large Taxpayers Field Operations Division' },
  { code: '123', name: 'RDO No. 123', location: 'Excise Large Taxpayers Audit Division' },
  { code: '124', name: 'RDO No. 124', location: 'Large Taxpayers Assistance Division' },
  { code: '125', name: 'RDO No. 125', location: 'Large Taxpayers Document Processing Division' },
  { code: '126', name: 'RDO No. 126', location: 'Large Taxpayers Collection Enforcement Division' },
  { code: '127', name: 'RDO No. 127', location: 'Puerto Princesa City, Palawan' },
];
